# Dataset
dataset: 'mmptrack_prw'
dataset_dir: '/mnt/backup/vi-team/taindp/mmptrack/'
train_set: 'trainval'
test_set: 'test'
retrieval_name_list: ('g50',)
runtime: '01_08_2023_18_06_08'
# OIM
oim_cq_size: 500

# Model
model: 'resnet'
backbone_arch: 'resnet'

# GFN
gfn_mode: 'combined'
gfn_query_mode: 'batch'
gfn_scene_pool_size: 56

# Optimization
epochs: 100
batch_size: 8
optimizer: ('sgd', 1e-3)

# Run mode
test_only: True

# Augmentation
aug_mode: 'rrc'
aug_crop_res: 512

# Logging
trial_name: 'mmptrack_prw_baseline'
eval_interval: 1
ckpt_interval: 1
log_dir: '/mnt/data2/taindp/data-centric/logs/mmptrack'
ckpt_path: '/mnt/data2/taindp/data-centric/code/GFN/logs/mmptrack_prw/01_07_2023_17_53_51/epoch_18.pkl'
